### ISSUE TITLE
Cyberpunk 2077 - Mouse & Keyboard don't work

### ISSUE THREAD

**Issue by Kaydax** [Melechtna/Proton-with-Wayland#1]
I'm running Cyberpunk 2077 via Steam, the game launches and I can use my mouse and keyboard only before the main menu, when getting to the main menu, both the mouse and keyboard stop working in game. 

Here are my launch options:
`unset DISPLAY && ENABLE_HDR_WSI=1 DXVK_HDR=1 %command% --launcher-skip -skipStartScreen`

**Comment by Melechtna** [comment]
I have very little control over this, and this entire repository is primarily meant as a "this is likely broken" set of releases, primarily to get ahold of Wayland in wine before it becomes the norm, which looks to be increasingly Soon™. So it's very unlikely I'm going to be able to, or even up to, handling such issues, as that's not really the point of these.
